[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 9002

[[plugins]]
  package = "@netlify/plugin-nextjs"
